[박지민] 1. 입출력
InhaBas/2022-winter-algorithm-study pull request #13
Opened 2022-01-06 01:38 UTC by JIMIN58

2022-01-06 02:05 UTC, Dong-Hyeon-Yu requested changes
리뷰 달아드렸습니다~ 낯선 git과 씨름하느라 고생 많으셨어요 ㅠㅠ
이항연산자 띄어쓰기 부분만 컨벤션 참고해서 다시 고쳐볼까요??

(수정사항 반영 후 기존 브런치에 커밋하고 푸쉬하면, 이 PR은 건들이지 않아도 변경이 반영됩니다! )

2022-01-06 02:05 UTC, Dong-Hyeon-Yu commented on 1st.py
> +print(a*b)
이항 연산자 띄어쓰기에 관한 코드 컨벤션을 참고해주세요(https://www.python.org/dev/peps/pep-0008/#other-recommendations)

위의 코드를 컨벤션에 맞게 고치면 아래와 같이 작성할 수 있겠네요
```python
print(a * (b%10))
print(a * int((b%100 - b%10) / 10))
print(a * (b//100))
print(a * b)
```
꽤 보기 좋아졌죠?? 코드를 읽기 쉽게 작성해보아요 😀

2022-01-06 08:49 UTC, shs1018 approved these changes

2022-01-07 05:29 UTC, Dong-Hyeon-Yu approved these changes
고생하셨습니다~

2022-01-07 05:29 UTC, Dong-Hyeon-Yu commented on 1st.py
> +# 이항 어쩌구 수정
이항 어쩌구가 아니라,,
이항 연산자에 관한 코드 컨벤션이죠..ㅎ
다음부터는 잘 적용시켜 주세요~ :+1:

2022-01-07 05:43 UTC, merged