[윤예진] 2. if문
InhaBas/2022-winter-algorithm-study pull request #21
Opened 2022-01-09 04:22 UTC by Yejin0O0

허겁지겁 PR

2022-01-09 12:14 UTC, YangTaeyoung requested changes

2022-01-09 12:14 UTC, YangTaeyoung commented on LEVEL2/2753.py
> +if (year % 4) == 0 and (year % 100) != 0: # 4의 배수이면서 100의 배수가 아닐 때
and를 쓸 수 없다고 가정하면 어떻게 코드를 짜면 될까요?
어떤게 더 효율적인가요?

2022-01-09 12:14 UTC, YangTaeyoung commented on LEVEL2/2884.py
> +if m > 44:
```suggestion
if m >= 45:
```
이렇게 바꾸는 것이 더 맞는 의미 입니다.

2022-01-09 12:14 UTC, YangTaeyoung commented on LEVEL2/2884.py
> +elif (m < 45) and (h > 0):
elif, else 문은 이전의 if문이 거짓임을 내포하고 있기 때문에
`m < 45`와 같은 코드는 앞서서 거짓임을 말했기 때문에 필요 없겠지요.

2022-01-09 12:33 UTC, Yejin0O0 commented on LEVEL2/2884.py
> +elif (m < 45) and (h > 0):
아 그렇네요. 당연히 써야한다고 생각했어요

2022-01-09 19:47 UTC, YangTaeyoung approved these changes

2022-01-09 19:47 UTC, YangTaeyoung commented on LEVEL2/14681.py
> +    print(4)
프로그래머는 항상 효율적인 코드와 깔끔한 코드 사이에서 고민해야 하는 직업인 것 같습니다.
분명 써주신 코드가 깔끔한 코드임에는 맞으나, 효율성으로 따져본다면 많은 연산이 필요한 코드입니다.
```python
if (x > 0) and (y > 0):
```
해당연산에는 x>0인지를 판단하는 연산 1회, y>0에서 판단하는 연산 1회로 총 2회의 연산이 필요하며
최악의 경우 `else`부분으로 가면 7회의 연산이 필요합니다.

그럼 아래 코드를 보도록 하죠
``` python 
if x > 0:
    if y > 0:
        print(1)
    else:
        print(3)
else:
    if y > 0:
        print(2)
    else:
        print(4)
```

해당 부분에서는 각 if당 1회의 연산이 필요하며, 4분위 수(최악의 경우)가 되기 위해 걸리는 연산의 횟수는 5회입니다. 
해당 문제는 굉장히 쉬운 부분처럼 보이나 실무 코딩에서는 성능 개선을 위해 밤낮으로 고민해야 하는 부분이기도 합니다.
 
만약 해당 if문이 for문 속에 존재하며 해당 for문은 요소 1000만개짜리의 리스트에 존재한다고 가정해봅시다.
(실무에서는 실제 데이터베이스가 되겠지요)
첫번째 안은 7000만개의 연산이 필요하나,
두번째 안은 5000만개의 연산이 필요하게 되겠죠.
시간으로 따지면 7시간이 5시간이 되는 것이겠죠.

물론 반대의 경우도 있습니다.
데이터가 적은 개수겠죠.
만약 500개의 데이터만 필요하다면, 굳이 길게 적을 필요가 없겠죠.
가시성이 좋은 1안을 채택하는 것이 유지보수에 도움이 될 겁니다.

앞으로 어떻게 하면 더 효율적인지, 어떻게 하면 더 클린한 코드인지를 생각하며 개발에 임하도록 합시다!

2022-01-10 18:27 UTC, Dong-Hyeon-Yu approved these changes
고생하셨습니다~

2022-01-10 18:27 UTC, Dong-Hyeon-Yu commented on LEVEL2/2884.py
> +    print(23, 15 + m) # 0시일 때 가정. 45분보다 작아 시에서 1을 빼야하므로 23시라 두었음.
고민했던 흔적이 너무 좋네욯ㅎ
if 문 하나 더 줄일 수 있어요~~! :grin: 
```suggestion
else:
    print((h-1) % 24, 15 + m) # 45분보다 작으면 시에서 1을 빼야함
```

2022-01-10 18:27 UTC, Dong-Hyeon-Yu commented on LEVEL3/10871.py
> +        print(i, end=" ") # 개행(newline)을 원치 않을 때는 print 함수의 매개변수로 end='' 를 추가해주면 된다.
뭘 알게되었는지 적어두는 것도 좋네요! :+1:

아래와 같이 작성할수도 있어요! 참고! 무조건 더 좋은 방식이라는 건 아니에요! 
```python
n, x = map(int, input().split())

for i in input().split(): 
    if int(i) < x:
        print(i, end=" ") 
```

2022-01-11 03:03 UTC, shs1018 approved these changes
확인했습니다!

2022-01-15 10:03 UTC, merged