[윤예진] 5. 1차원 배열
InhaBas/2022-winter-algorithm-study pull request #30
Opened 2022-01-14 16:44 UTC by Yejin0O0

바보멍청이윤예진

2022-01-14 17:22 UTC, shs1018 commented on LEVEL5/10818.py
> +# 정렬 후 제일 작은 건 최솟값, 제일 큰건 최댓값임. n-1을 해야 맨 마지막 원소 찾기 가능함
sorted 함수로도 최소/최댓값을 구해 낼 수 있군요!

2022-01-14 17:30 UTC, shs1018 commented on LEVEL5/8958.py
> +    print(sumScore)
제가 한 것보다 훨씬 깔끔하게 하셨네요!

2022-01-14 17:30 UTC, shs1018 approved these changes

2022-01-14 17:37 UTC, shs1018 approved these changes

2022-01-15 10:47 UTC, Dong-Hyeon-Yu approved these changes
공부 많이 한 흔적이 보이네요 ㅠㅠ 고생했습니다~~
시간복잡도에 대한 질문을 하나 했어요~ 
고민해보면 좋은 부분이에요!!

2022-01-15 10:47 UTC, Dong-Hyeon-Yu commented on LEVEL5/10818.py
> +print(sortList[0], sortList[n - 1])
파이썬은 인덱싱 할때 음수로 뒤에서부터 접근 가능합니다~
```suggestion
# 정렬 후 제일 작은 건 최솟값, 제일 큰건 최댓값임. n-1을 해야 맨 마지막 원소 찾기 가능함
print(sortList[0], sortList[-1])
```

2022-01-15 10:47 UTC, Dong-Hyeon-Yu commented on LEVEL5/2562.py
> +    aList.append(int(input())) #input 9번 생성 후 삽입
관례상 반복문 변수가 의미가 없을 때는 underscore 를 사용합니다
```suggestion
for _ in range(9):
    aList.append(int(input())) #input 9번 생성 후 삽입
```

2022-01-15 10:47 UTC, Dong-Hyeon-Yu commented on LEVEL5/2577.py
> +    # 참고한 사이트: https://blockdmask.tistory.com/410
`collections `모듈의 `Counter` 라는 것도 알아보면 도움이 많이 될 듯 합니다! 
빈도수를 구해서 딕셔너리로 반환해주거든요!

2022-01-15 10:47 UTC, Dong-Hyeon-Yu commented on LEVEL5/3052.py
> +        pass # 아니면 pass
이 부분의 시간 복잡도는 어떻게 될까요~?
시간 복잡도를 어떻게 더 줄일 수 있을까요 ??

2022-01-15 10:47 UTC, Dong-Hyeon-Yu commented on LEVEL5/4344.py
> +    avg = sum(score[1:]) / score[0]  # score[0]: 학생수, score[1:] 점수
이런 주석 좋아요 👍 👍

2022-01-20 12:26 UTC, YangTaeyoung requested changes
잘했지만 질문에 답을 안하셨군요. 기각.

2022-01-20 12:26 UTC, YangTaeyoung commented on LEVEL5/10818.py
> +# 정렬 후 제일 작은 건 최솟값, 제일 큰건 최댓값임. n-1을 해야 맨 마지막 원소 찾기 가능함
sorted 함수로 최대 최소를 구하는 것은 비효율적이에요.
단순 최대/최소를 구한다면 두개의 값을 뽑는 연산만 수행하면 되지만
sorted 함수는 다른 요소의 순서를 고려하는 단계에서 추가적인 연산이 소요되기 때문에 연산이 복잡한 편이에요.

나중에 알고리즘을 배울 때 시간 복잡도 부분을 학습하면 도움이 되겠네요.
max, min 함수를 사용하는 게 더 좋을 것 같네영

2022-01-20 12:26 UTC, YangTaeyoung commented on LEVEL5/2562.py
> +    aList.append(int(input())) #input 9번 생성 후 삽입
그리고 리스트 컴프리핸션이 가능하죠
```python
aList = [int(input()) for _ in range(9)]
```

2022-01-20 12:26 UTC, YangTaeyoung commented on LEVEL5/2562.py
> +print(max(aList))
max 함수에는 key로  최대값을 찾는 순서를 정할 수 있어요
예를 들어 3*2크기의 2차원 배열이 다음과 같이 있다고 할 때
```python
aList = [
    [1, 2],
    [3, 4],
    [5, 6]
]
```
각 row의 1번 요소([2,4,6])를 기준으로 최댓값을 뽑고 싶다면 
람다 함수를 활용해서 다음과 같이 작성할 수 있어요
```python
max(aList, key=lambda x: x[1])
```

2022-01-20 12:26 UTC, YangTaeyoung commented on LEVEL5/3052.py
> +        pass # 아니면 pass
다음의 답을 Big O notation으로 점근적분석방식에 의거하여 설명하시오.(5점)

2022-01-27 07:31 UTC, merged