7. 문자열
InhaBas/2022-winter-algorithm-study pull request #36
Opened 2022-01-19 04:26 UTC by JIMIN58

2022-01-19 11:12 UTC, Dong-Hyeon-Yu approved these changes
2675번은 뭔가 정리가 안된 느낌이네요..? ㅎㅎ for 문 들여쓰기도 잘 안되어 있어요 😢 

그 문제만 제외하면,
전체적으로 코드도 깔끔하고, 파일도 분리되어 있고, 
변수 네이밍도 의미있게 잘 드러나서 좋네요!! 굳입니다 👍

2022-01-19 11:12 UTC, Dong-Hyeon-Yu commented on 1157.py
> +unique_words = list(set(words))  # 입력받은 문자열에서 중복값을 제거
알고 있던 `set` 을 활용하는 것 좋네요~~! 
이 문제에 대해서는 dictionary 를 활용해보는 것도 좋을거같아요
key - value 의 쌍을 요소로 갖는 자료구조에요
key 는 알파벳, value 는 해당 알파벳의 빈도수라고 생각을 하면 되겠네요!
```python 
from collections import defaultdict

cnt_dict = defaultdict(int)
for alphabet in words:
    cnt_dict[alphabet]++
```

2022-01-20 14:03 UTC, YangTaeyoung requested changes
문제에 답해보세요!

2022-01-20 14:03 UTC, YangTaeyoung commented on 6.py
> +    a.append(k)
변수의 선언은 두 군데 이상 공통적인 변수가 들어간 경우 새롭게 해주는 것이 좋아요
변수 `k`의 경우 for문 안에서만 사용하고 있는 변수이기 때문에 따로 선언하지 않고 다음과 같이 줄여서 쓸 수 있어요
```python
for i in range(1, 10001): 
     a.append(d(i))
```
여기서 for문의 역할은 빈 리스트 a에 요소를 추가하며 새로운 리스트를 만드는 목적에만 사용하고 있기 때문에 리스트 컴프리헨션을 사용하여 다음과 같이 줄일 수 있어요
```python
a = [ d(i) for i in range(1, 10001) ]
```

2022-01-20 14:03 UTC, YangTaeyoung commented on 6.py
> +    for x in list(str(n)):
문자열(str)형 자료형의 경우 이미 iterable한 객체이기 때문에 list로 형변환할 필요는 없어요
```suggestion
    for x in str(n):
```

2022-01-22 02:12 UTC, JIMIN58 commented on 10809.py
> +# find 함수와 다른 점은 찾는 문자가 문자열 안에 포함되지 않는 경우 -1(find 함수의 반환값), index 함수는 >AttribueError로 반환
둘 다 어려워서 검색의 힘을 빌렸더니................
1. 문자열이 안에 있는지 아닌지 확인할 때 사용할 수 있습니다!
2. try expect문으로 에러가 뜨면 break로 나가게 할 수 있지 않을까요...?

2022-01-22 02:20 UTC, JIMIN58 commented on 2908.py
> +b = int(b[::-1])
range 함수와 시작 인덱스:끝 인덱스:증가할 단위 < 이 구조가 비슷한 것 같습니다!

2022-01-22 08:37 UTC, YangTaeyoung approved these changes

2022-01-22 08:37 UTC, YangTaeyoung commented on 2908.py
> +b = int(b[::-1])
@JIMIN58 정답이에요!

2022-01-22 08:37 UTC, YangTaeyoung commented on 10809.py
> +# find 함수와 다른 점은 찾는 문자가 문자열 안에 포함되지 않는 경우 -1(find 함수의 반환값), index 함수는 >AttribueError로 반환
index 함수가 문자열 안에서도 돌 수 있군요 저도 검색을 통해 알게 되었습니다.
find 함수가 쓰이기 어려운 부분은 조건문이나 반복문(while) 내부에 해당 함수를 조건으로서 사용해야 하는 경우입니다.
예를 들어서 살펴보죠
변수 `s`에 문자열이 있다고 가정하였을 때 특정 문자 l이 s에 존재할 때 print()시키는 간단한 프로그램을 아래와 같이 구성해봅시다.
```python
s = "hello world"
if s.find("l") != -1:
     print(f"문자열 l이 변수 s의 {s.find('l')} 인덱스에 존재합니다.")
     ...
     ... (중략)
```
아래와 같이 조건문 안에 find 함수를 통해 분기하게 한다면 문자열이 존재하는 경우 인덱스를 반환하여 에러를 일으키지 않으나,
문자열이 존재하는 경우 반드시 프로그램이 종료되게 됩니다.
그렇기 때문에 아래와 같이 try except문을 통하여 다시 구성할 수 있습니다.

```python
s = "hello world"
try: 
if s.find("l") != -1:
     print(f"문자열 l이 변수 s의 {s.find('l')} 인덱스에 존재합니다.")
     ...
     ... (중략)
except ValueError:
     pass
```
해당 방식처럼 구성하면 기존 의도대로 가긴 하나 문제점이 있습니다.
만약 if문 속에도 ValueError를 일으키는 함수나, 문구가 있다면 어떻게 할까요?
if문의 조건문 안에서 ValueError가 발생하는지 아니면 if문 속 다른 문장이 일으키는지 프로그래머가 파악하기 힘들 것입니다.
물론 방법은 굉장히 많기 때문에 try except를 통해 if문처럼 처리할 수 있으나, try except문의 경우 꼭 예외처리를 해야하는 경우에만 사용하도록 권장하고 있으며, if 문처럼 사용하는 것을 권장하지 않고 있습니다.

따라서 조건문이나 반복문 내부에 사용하는 것은 예외 상황을 제어하기 용이한 index함수를 쓰는 것이 더 좋겠죠?

2022-01-22 08:37 UTC, YangTaeyoung commented on 10809.py
> +# find 함수와 다른 점은 찾는 문자가 문자열 안에 포함되지 않는 경우 -1(find 함수의 반환값), index 함수는 >AttribueError로 반환
그럼 이제 문자열을 인덱싱한다고 가정하고 생각해봅시다
s = "hello world"
s[*]
* 안에 find, index 함수 둘 중 하나를 선택하여 인덱싱을 한다고 가정 하였을 때
어떤 함수를 선택해야 좀 더 맞을까요?

2022-01-22 08:44 UTC, YangTaeyoung approved these changes
Good

2022-01-22 08:44 UTC, YangTaeyoung commented on 8/1011.py
> +        if count % 2 == 0 :  # count가 2의 배수일 때
조건문, 반복문 while 안의 0은 `False`, 1은 `True`로 인식되기 때문에
```python
if not count % 2:
```
으로 고쳐쓸 수 있습니다.

2022-01-27 07:32 UTC, merged