1. 입출력과 사칙연산
InhaBas/2022-winter-algorithm-study pull request #7
Opened 2022-01-05 01:08 UTC by shs1018

2022-01-05 01:11 UTC, shs1018 commented
수정 중입니다...

2022-01-05 01:19 UTC, Dong-Hyeon-Yu commented on 1. 입출력과 사칙연산.py
> +print(A+B)
이항 연산자 사이에서는 띄어쓰기 해주세요!
```python
print(A + B)
```

2022-01-05 01:20 UTC, Dong-Hyeon-Yu commented on 1. 입출력과 사칙연산.py
> +print(((A%C)+(B%C))%C)
이런 경우에는 가독성을 위해 아래와 같이 작성하셔야 합니다!
```python
print(((A%C) + (B%C)) % C)
```

2022-01-05 01:23 UTC, Dong-Hyeon-Yu requested changes
`.idea` 폴더는 pycharm이 프로젝트 인덱싱 등을 위해 사용하는 폴더입니다. 
커밋 내역과는 무관하므로 .gitignore 파일 작성해서 커밋되지 않도록 변경해주세요!

또 리뷰 몇개 더 달았으니까 수정사항 반영해주시면 좋겠습니다~! :+1:

2022-01-05 01:25 UTC, Dong-Hyeon-Yu commented on 1. 입출력과 사칙연산.py
> +#1.
빈 줄을 하나 더 줘서 구분하는 것도 나쁘지 않겠네요!
코드는 읽기 편해야 합니다!

2022-01-05 01:33 UTC, Dong-Hyeon-Yu commented on 1. 입출력과 사칙연산.py
> +print(((A%C)+(B%C))%C)
https://www.python.org/dev/peps/pep-0008/#other-recommendations
이 부분에 해당하는
공식 레퍼런스에 나와있는 코드 컨벤션 입니다.
참고하시면 좋을 듯 해요 :smile:

2022-01-05 02:24 UTC, Dong-Hyeon-Yu approved these changes
수정사항 잘 반영해주셨네요! :+1: 

gitignore 파일에 대해서 한번 검색해보시면 좋을  듯 합니다! 아직은 git이 익숙하지 않아서 완벽하게 숙지하실 필요는 없지만, 이런게 있다 정도는 알고 계시면 나중에 도움이 될 듯해요!

추가로 앞으로 커밋 메세지 작성할 때는 의미있는 메세지를 써주시면 더 좋을거같아요! 
예를 들면 "`수정요구사항 반영 - 이항 연산자 사이의 띄어쓰기`" 등등 말이죠!

고생하셨습니다~~ :smile:

2022-01-05 03:42 UTC, YangTaeyoung requested changes
IDE 관련 파일 삭제하시길 바라며,
그룹 2는 원래 출력부분부터 하는 것으로 된 건가여?? 허허

2022-01-05 03:42 UTC, YangTaeyoung commented on .idea/.gitignore
> +/dataSources.local.xml
깃 이그노어는 커밋 전에 해당 부분을 세팅하여야 하며 해당 부분은 https://www.toptal.com/developers/gitignore 에서 자신이 사용하는 IDE나 언어 예) PyCharm, Python 등을 입력하면 gitignore에 들어가는 요소들을 간략하게 살펴볼 수 있습니다. 
git에 팀원과 공유할 특별한 목적이 있지 않는 이상 세팅 파일은 원격저장소에서 제거해주시길 바립니다.
아래 리뷰한 파일을 삭제후 커밋-푸시 하시면 됩니다.

2022-01-05 03:42 UTC, YangTaeyoung commented on .idea/2022-winter-algorithm-study.iml
> +</module>
해당 파일 삭제해주세요

2022-01-05 03:42 UTC, YangTaeyoung commented on .idea/inspectionProfiles/profiles_settings.xml
> +</component>
해당 파일 삭제해주세요

2022-01-05 03:42 UTC, YangTaeyoung commented on .idea/misc.xml
> +</project>
해당 파일 삭제해주세요

2022-01-05 03:42 UTC, YangTaeyoung commented on .idea/modules.xml
> +</project>
해당 파일 삭제해주세요

2022-01-05 03:42 UTC, YangTaeyoung commented on .idea/vcs.xml
> +</project>
해당 파일 삭제해주세요

2022-01-05 03:43 UTC, YangTaeyoung requested changes
.

2022-01-06 08:51 UTC, shs1018 commented on .idea/.gitignore
> +/dataSources.local.xml
넵 더 알아보고 진행하도록 하겠습니다!

2022-01-06 12:24 UTC, YangTaeyoung approved these changes
고생했어요 👍👍

2022-01-07 05:26 UTC, merged